# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('post', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
